apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avon-dev
  namespace: argocd
spec:
  destination:
    namespace: avon-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mngt-cluster/clusters/avon-dev
    repoURL: https://github.com/thradec/atc-gitops-poc.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true