apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avon-prod
  namespace: argocd
spec:
  destination:
    namespace: avon-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mngt-cluster/clusters/avon-prod
    repoURL: https://github.com/thradec/atc-gitops-poc.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true