apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heineken-test
  namespace: argocd
spec:
  destination:
    namespace: heineken-test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mngt-cluster/clusters/heineken-test
    repoURL: https://github.com/thradec/atc-gitops-poc.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
